###### Templates
## Service
x-service-template: &service_template
  build:
    context: .
    dockerfile: Dockerfile
    target: ${SERVICE}-service
    args:
      SERVICE: ${SERVICE}
  env_file:
    - ./.env.example
  environment:
    DB_HOST: ${SERVICE}-db
  depends_on:
    - ${SERVICE}-db
  healthcheck:
    test: ["CMD-SHELL", "nc -z localhost 50051"]
    interval: 5s
    timeout: 2s
    retries: 10
    start_period: 5s
  networks:
    - app-network

## DB
x-db-template: &db_template
  image: postgres:13-alpine
  env_file:
    - .env.example
  # volumes:
  # ## TODO(HI): make interchangeable
  #   - "${SERVICE}_data:/var/lib/postgresql/data"
  networks:
    - app-network
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
    interval: 10s
    timeout: 5s
    retries: 5

###### Deployments

#### USER
## DB
services:
  user-db:
    <<: *db_template
    container_name: user-db
    volumes:
      - user_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

## Service
  user-service:
    <<: *service_template
    container_name: user-service
    ports:
      - "50051:50051"
    depends_on:
      user-db:
        condition: service_healthy

#### OPERATION
## DB
  operation-db:
    <<: *db_template
    container_name: operation-db
    volumes:
      - operation_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

## Service
  operation-service:
    <<: *service_template
    container_name: operation-service
    ports:
      - "50052:50051"
    depends_on:
      operation-db:
        condition: service_healthy
      user-service:
        condition: service_healthy

volumes:
  user_data:
  operation_data:

networks:
  app-network:
    driver: bridge
